### ISSUE TITLE
Avoid bundling GraphiQL

### ISSUE THREAD

**Issue by Jomik** [contra/graphql-helix#203]
Hey!
Would it be possible to avoid bundling GraphiQL directly, but simply have it as an (optional?) peer dependency?
I am currently having some issue using `defer` with the latest version of GraphQL Helix and GraphQL 16 (experimental). I suspect this is due to helix using an outdated version of GraphiQL?
Why does it have to be a direct dependency? Could `renderGraphiQL` not simply take an argument, or make use of a peer dependency?

**Comment by saihaj** [comment]
> Would it be possible to avoid bundling GraphiQL directly

yes once we have https://github.com/contra/graphql-helix/pull/140

> I am currently having some issue using defer with the latest version of GraphQL Helix and GraphQL 16 (experimental).

Helix comes with support for defer and stream with whatever is the latest tag for v16 experimental. Is there a particular functionality that is broken for you?

**Comment by Jomik** [comment]
It simply 'does not work'.
I have a query where I tagged a fragment with defer, and I see that it still waits for the full thing. `processRequest` also simply returns a `RESPONSE`.
I am unsure if I missed something.
I use [GiraphQL](https://giraphql.com/) to build my schema.

**Comment by Jomik** [comment]
Aaaand, it seems to be due to me having `useGraphQlJit` in my envelop.
Removing that makes defer work.
https://www.envelop.dev/plugins/use-graphql-jit
