### ISSUE TITLE
processRequest does not support multiple accept types

### ISSUE THREAD

**Issue by Jomik** [contra/graphql-helix#204]
The currently bundle GraphiQL sends multiple accept types when sending a request:
Slightly related to #203 

See https://github.com/contra/graphql-helix/blob/89707735b61848eae3b28dc06747c0509306fe20/packages/core/lib/process-request.ts#L90
I currently get `accept = 'application/json, multipart/mixed, text/event-stream'`
Maybe this should be updated to use `includes`.
Also, is there a reason to not check for `multipart/mixed`?

**Comment by Jomik** [comment]
Fixed by #160 I assume

**Comment by n1ru4l** [comment]
This is now fixed within https://github.com/contra/graphql-helix/releases/tag/graphql-helix%401.11.0
